#!/bin/bash

meson . build
meson configure -Dprefix=$PWD/build/testdir build
ninja -C build
ninja -C build install
GTK_THEME=Adwaita ninja -C build run &
sleep 10
gnome-screenshot -w -f website/screenshots/mainwindow.png

xdotool key --delay 100 Tab Shift+Tab Shift+Tab Shift+Tab Shift+Tab Return
sleep 0.5
gnome-screenshot -w -f website/screenshots/add_feed.png
sleep 3

xdotool key --delay 100 Escape Tab Tab Return Down
sleep 0.5
gnome-screenshot -w -f website/screenshots/import_export.png
sleep 3

xdotool key --delay 100 Escape Tab Tab Return
sleep 3
gnome-screenshot -w -f website/screenshots/webview.png
sleep 3

xdotool key --delay 100 Shift+Tab Shift+Tab Shift+Tab Shift+Tab Return
sleep 3
gnome-screenshot -w -f website/screenshots/reader.png
sleep 3

xdotool key --delay 100 Tab Return
sleep 3
gnome-screenshot -w -f website/screenshots/rss_content.png
sleep 3

xdotool key --delay 100 Shift+Tab Shift+Tab Return Down Down Down Return
sleep 1
gnome-screenshot -w -f website/screenshots/preferences.png
sleep 3

xdotool key Alt+F4 # closes preferences
sleep 1

# xdotool key --delay 100 Shift+Tab Shift+Tab Shift+Tab Return
# sleep 1
# xdotool key --delay 100 Tab Tab Return
# sleep 3
# gnome-screenshot -w -f website/screenshots/filter.png
# sleep 3

xdotool key Alt+F4
